//Friends Profile Data Array

export const FriendsProfileData = [
    {
        name: 'Zenshi',
        accountName: 'Zenshi',
        profileImage: require('../storage/images/profile1.jpg'),
        posts: 30,
        followers: 2000,
        following: 50,
        follow: false,
    },
    {
        name: 'Syntaxage',
        accountName: 'Syntaxage',
        profileImage: require('../storage/images/profile2.jpg'),
        posts: 40,
        followers: 300,
        following: 10,
        follow: false,
    },
    {
        name: 'The_Tom',
        accountName: 'Tom',
        profileImage: require('../storage/images/profile3.jpg'),
        posts: 23,
        followers: 400,
        following: 50,
        follow: false,
    },
    {
        name: 'Live_Long',
        accountName: 'Live Long',
        profileImage: require('../storage/images/profile4.jpg'),
        posts: 56,
        followers: 2100,
        following: 653,
        follow: false,
    },
    {
        name: 'The_Dominus',
        accountName: 'Dominus',
        profileImage: require('../storage/images/profile5.jpg'),
        posts: 30,
        followers: 7600,
        following: 705,
        follow: false,
    },
    {
        name: 'The_Doll',
        accountName: 'Doll',
        profileImage: require('../storage/images/post5.jpg'),
        posts: 30,
        followers: 7600,
        following: 705,
        follow: false,
    },
    {
        name: 'Zenshi',
        accountName: 'Zenshi',
        profileImage: require('../storage/images/profile1.jpg'),
        posts: 30,
        followers: 2000,
        following: 50,
        follow: false,
    },
    {
        name: 'Syntaxage',
        accountName: 'Syntaxage',
        profileImage: require('../storage/images/profile2.jpg'),
        posts: 40,
        followers: 300,
        following: 10,
        follow: false,
    },
    {
        name: 'The_Tom',
        accountName: 'Tom',
        profileImage: require('../storage/images/profile3.jpg'),
        posts: 23,
        followers: 400,
        following: 50,
        follow: false,
    },
    {
        name: 'Live_Long',
        accountName: 'Live Long',
        profileImage: require('../storage/images/profile4.jpg'),
        posts: 56,
        followers: 2100,
        following: 653,
        follow: false,
    },
    {
        name: 'The_Dominus',
        accountName: 'Dominus',
        profileImage: require('../storage/images/profile5.jpg'),
        posts: 30,
        followers: 7600,
        following: 705,
        follow: false,
    },
    {
        name: 'The_Doll',
        accountName: 'Doll',
        profileImage: require('../storage/images/post5.jpg'),
        posts: 30,
        followers: 7600,
        following: 705,
        follow: false,
    },
];